### ISSUE TITLE
Setting an initial value

### ISSUE THREAD

**Issue by ajoslin** [noffle/hyper-string#3]
I'd like to be able to set an initial value to the hyper-string. Use case, for example, is opening a file from the file system and loading it into a textarea.

After #1 (long string insertions) is supported, how would you do this? What do you think of an `String opts.initial` that inserts itself after `this.index.ready`?

Then `hyper-textarea` could pass in the textarea element's initial `.value` into `hyper-string`, and it would all "just work".

This could also all be done in hyper-textarea -- we could just not support an initial value, instead just pass `textareaNode.value` in from the hyper-textarea once the index is ready.

**Comment by hackergrrl** [comment]
How would an initial value (are you thinking constructor?) differ from inserting a big list of chars after creating the hyper-string? Maybe I don't understand the semantics you had in mind.

I worry about initial values in general because the client can't dedupe the initial value from what may already be present in the string, and produce repeated garbage. Example steps:
1. I load up hyperpad.io?doc=foobar and the initial value logic writes "Welcome to hyperpad!" to the log.
2. I open another tab with the same URL in Incognito. While it's connecting to signalhub or even just loading from indexeddb, my client inserts that same "Welcome to hyperpad!" text into my local string.
3. I replicate the tabs together, and now the final string is "Welcome to hyperpad!Welcome to hyperpad!".

**Comment by ajoslin** [comment]
Fair enough. I was just thinking it could take the initial value from the textarea -- but I think I agree, doing it manually is a much "safer" way. :+1:

Unless a really good use case comes up, no need to complicate the API.
